
  CREATE TABLE "REL"."TABLE_COMPARE_CHECKLOG" 
   (	"STABLE" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"TTABLE" VARCHAR2(4000 BYTE) NOT NULL ENABLE, 
	"S_FIELD" VARCHAR2(80 BYTE), 
	"T_FIELD" VARCHAR2(80 BYTE), 
	"SGB_FIELDS" VARCHAR2(80 BYTE), 
	"TGB_FIELDS" VARCHAR2(80 BYTE), 
	"S_VALUE" NUMBER, 
	"T_VALUE" NUMBER, 
	"SGB_VALUE" VARCHAR2(80 BYTE), 
	"TGB_VALUE" VARCHAR2(80 BYTE), 
	"COMPARE_DATE" VARCHAR2(10 BYTE), 
	"COMPARE_TIME" VARCHAR2(8 BYTE), 
	"CHECK_NAME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KEDM_RELEASED" ;

   COMMENT ON COLUMN "REL"."TABLE_COMPARE_CHECKLOG"."STABLE" IS '源表名';
   COMMENT ON COLUMN "REL"."TABLE_COMPARE_CHECKLOG"."TTABLE" IS '目标表名';
   COMMENT ON COLUMN "REL"."TABLE_COMPARE_CHECKLOG"."S_FIELD" IS '源表对比字段';
   COMMENT ON COLUMN "REL"."TABLE_COMPARE_CHECKLOG"."T_FIELD" IS '目标表对比字段';
   COMMENT ON COLUMN "REL"."TABLE_COMPARE_CHECKLOG"."SGB_FIELDS" IS '源表分组字段集，逗号分隔';
   COMMENT ON COLUMN "REL"."TABLE_COMPARE_CHECKLOG"."TGB_FIELDS" IS '目标表分组字段集，逗号分隔';
   COMMENT ON COLUMN "REL"."TABLE_COMPARE_CHECKLOG"."S_VALUE" IS '源表数据值';
   COMMENT ON COLUMN "REL"."TABLE_COMPARE_CHECKLOG"."T_VALUE" IS '目标表数据值';
   COMMENT ON COLUMN "REL"."TABLE_COMPARE_CHECKLOG"."SGB_VALUE" IS '源表分组字段值';
   COMMENT ON COLUMN "REL"."TABLE_COMPARE_CHECKLOG"."TGB_VALUE" IS '目标表分组字段值';
   COMMENT ON COLUMN "REL"."TABLE_COMPARE_CHECKLOG"."COMPARE_DATE" IS '比较日期';
   COMMENT ON COLUMN "REL"."TABLE_COMPARE_CHECKLOG"."COMPARE_TIME" IS '比较时间';
   COMMENT ON COLUMN "REL"."TABLE_COMPARE_CHECKLOG"."COMPARE_METHOD" IS '比较方法';

   